import { z } from 'zod';
import { agentStates } from '@local-agent/shared-types';
export const eventTypes = [
  'TASK_RECEIVED',
  'TASK_ANALYSIS_STARTED',
  'TASK_ANALYSIS_COMPLETED',
  'SKILL_SEARCH_STARTED',
  'SKILL_CANDIDATE_FOUND',
  'SKILL_SELECTED',
  'SKILL_NOT_FOUND',
  'PLAN_GENERATION_STARTED',
  'PLAN_GENERATED',
  'PLAN_APPROVAL_REQUIRED',
  'PLAN_APPROVED',
  'PLAN_REJECTED',
  'PLAN_VALIDATION_FAILED',
  'EXECUTION_STARTED',
  'STEP_STARTED',
  'STEP_COMPLETED',
  'STEP_FAILED',
  'STEP_RETRYING',
  'EXECUTION_CANCELLED',
  'RESULT_VALIDATION_STARTED',
  'RESULT_VALIDATION_COMPLETED',
  'TASK_COMPLETED',
  'TASK_FAILED',
  'SKILL_EMBEDDING_STARTED',
  'SKILL_EMBEDDING_COMPLETED',
  'SKILL_RANKING_COMPLETED',
  'SKILL_CREATION_PROPOSAL_GENERATED',
  'SKILL_TEST_CASES_GENERATED',
  'SKILL_EVALUATION_COMPLETED',
  'SKILL_APPROVAL_REQUIRED',
  'SKILL_AUTO_INSTALLED',
  'PERMISSION_APPROVAL_REQUIRED',
  'PERMISSION_GRANTED',
  'PERMISSION_REJECTED',
  'SKILL_APPROVED',
  'SKILL_REJECTED',
  'SKILL_VERSION_CREATED',
  'SKILL_ROLLED_BACK',
] as const;
export const agentEventSchema = z.object({
  id: z.string(),
  taskId: z.string(),
  type: z.enum(eventTypes),
  state: z.enum(agentStates),
  message: z.string(),
  timestamp: z.string(),
  sequence: z.number().int().positive(),
  payload: z.unknown().optional(),
});
export type AgentEvent = z.infer<typeof agentEventSchema>;
